# HOMEWORK 1


# 1.

In [2]:
import datetime
import time

cache = {}
def factorial(n):
    assert type(n) == int
    assert n >= 0   
    if n in cache.keys():
        return cache[n]
    if n == 0:
        return 1
    result = n * factorial(n-1)
    cache[n] = result
    return result
    
before = datetime.datetime.now()
s = factorial(1000)
after = datetime.datetime.now()
print(after -  before)

factorial(6)

0:00:00.002001


720

# 2.


In [3]:
class X:
    
    def __init__(self):
        pass
    
    def attr1(self):
        a = 3
        return a
    
    def attr2(self):
        return 18
    
    def _hd(self):
        return 4
    

    
x = X()    
  
def func(x):
    d = {}
    for i in x.__class__.__dict__.keys():
        if i[0] != '_' or i[1] != '_':
            d[i] = x.__getattribute__(i)()
    return d

func(x)

{'_hd': 4, 'attr1': 3, 'attr2': 18}

# 3.

In [4]:
import numpy as np

class Rotation():
    def __init__(self,angle):
        self.angle = angle
    
    def __call__(self,matrix):
        q = np.eye(matrix.shape[1])[::-1]
        
        if self.angle % 360 == 90:            
            return matrix.T.dot(q)
        
        if self.angle % 360 == 180:
            return (q.T.dot(matrix)).dot(q)
        
        if self.angle % 360 == 270:
            return q.T.dot(matrix.T)
        
        if self.angle % 360 == 0:
            return matrix
            
        
        
rot90 = Rotation(2250)
M1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
M2 = np.array([[4,8,9,6],[8,6,9,3],[1,2,5,9],[8,5,2,6]])
print(rot90(M1))
print(rot90(M2))

[[7. 4. 1.]
 [8. 5. 2.]
 [9. 6. 3.]]
[[8. 1. 8. 4.]
 [5. 2. 6. 8.]
 [2. 5. 9. 9.]
 [6. 9. 3. 6.]]


# 4.


In [11]:
def singleton(class_):
    instances = {}
    def getinstance(*args, **kwargs):
        if class_ not in instances:
            instances[class_] = class_(*args, **kwargs)
        return instances[class_]
    return getinstance

@singleton
class complex:
    def __init__(self,real,imag):
        self.r = real
        self.i = imag
        
    
a = complex(5,6)
print(a.r,a.i)
b = complex(7,8)
print(b.r,b.i)

5 6
5 6
